export const scenes = {
  istanbul: { name: 'Istanbul', subtitle: 'BOSPHORUS BY NIGHT', alt: 'Istanbul 像素夜景：海峡、清真寺、灯笼与屋顶茶园', index: '01' },
  tokyo: { name: 'Tokyo', subtitle: 'NEON RAIN IN SHINJUKU', alt: 'Tokyo 像素夜景：电车、霓虹、樱花与雨中街道', index: '02' },
  sydney: { name: 'Sydney', subtitle: 'JACARANDA NIGHT ON THE HARBOUR', alt: 'Sydney 像素夜景：歌剧院、港湾大桥与蓝花楹', index: '03' },
};

export const capabilities = [
  { id: '01', category: 'scene', layer: '场景层', title: '城市夜景与基础播放', status: 'verified', badge: '实测', file: '01-istanbul.png', summary: '11 个城市、动态像素夜景、当地时间与在线人数。', observation: '已观察到 Istanbul 的动态画面、当地时间和人数更新，并验证播放与暂停。窄窗口显示部分场景，另补拍了三座城市的桌面全景。', value: '让浏览器具有可识别的空间与情绪，为工作、学习或放松建立环境。', limit: '当地时间不等于实时昼夜模拟。在线人数的统计准确性、渲染性能和长时间资源占用未审计。' },
  { id: '02', category: 'sound', layer: '声音层', title: '浏览器内实时音乐', status: 'documented', badge: '说明 / 脚本核对', file: '02-music-explanation.png', summary: '通过 Web Audio 组合和弦、鼓、贝斯与旋律，持续生成曲目。', observation: 'Music 面板说明实时合成；补充阅读线上 audio/engine.js 等脚本，确认存在编曲、音符调度与 Web Audio 合成。读取时 music/playlist.js 为空，另预留录制音轨入口。', value: '减少持续补充录制曲目的依赖，使声音成为可调整的系统能力。', limit: '只核对公开脚本的核心路径，未做完整源码审计或主观音质评价；实时合成不等于 AI 模型生成。耐听程度和重复感仍需验证。' },
  { id: '03', category: 'sound', layer: '声音层', title: '音乐能量与乐器组合', status: 'verified', badge: '实测', file: '03-vibe.png', summary: '三种能量档位，搭配完整乐队、无鼓或仅键盘。', observation: '将 Balanced 切换为 Upbeat 并换曲，观察到曲目参数从 79 BPM 变为 82 BPM。能量从下一首生效，乐器组合按界面说明在下一小节生效。', value: '用有限且容易理解的选项，适应阅读、写作和更活跃的工作状态。', limit: '已验证设置状态与曲目参数变化，没有评价实际听感或验证所有组合。' },
  { id: '04', category: 'sound', layer: '声音层', title: '环境声独立混音', status: 'verified', badge: '实测', file: '04-city-mixer.png', summary: 'Istanbul 的水、鸟、风、交通、船笛与海鸥分别可调。', observation: '音乐和环境声有独立总音量。将 Traffic 从 100% 调为 95%，数值即时变化，随后成功重置。', value: '保留城市的空间感，同时降低不适合当前任务的声音。', limit: '不同城市的声源可能不同；站内说明相同声源可跨城沿用设置，本次未单独验证。' },
  { id: '05', category: 'workflow', layer: '工作流层', title: '专注与睡眠计时', status: 'documented', badge: '部分实测', file: '05-focus-timer.png', summary: '25/5、50/10 工作休息循环，以及 15–90 分钟睡眠计时。', observation: '已启动 25 分钟专注，切换至 5 分钟休息并停止。界面提供轮次、剩余时间、跳过和停止。', value: '为持续运行的氛围增加明确的开始、休息和结束节奏。', limit: '未等待完整周期，未验证睡眠淡出、后台挂起和系统休眠后的行为；未发现专注统计或任务管理入口。' },
  { id: '06', category: 'workflow', layer: '工作流层', title: '候播列表与选曲', status: 'verified', badge: '实测', file: '06-up-next.png', summary: '预览五首曲目的名称、调性、BPM 和时长，直接指定播放。', observation: '选择 hazy wishes 后，播放器更新为该曲目，并显示 D major、88 BPM。', value: '提供适量的自主选择，减少使用者反复寻找音乐的成本。', limit: '检查范围内未发现收藏、自建歌单、曲库搜索、自有音乐上传或音频导出入口。' },
  { id: '07', category: 'scene', layer: '场景层', title: '自动游城与跟随夜晚', status: 'verified', badge: '实测', file: '07-city-tour.png', summary: '定时切城，或寻找当地时间最接近凌晨 1 点的城市。', observation: '开启 Follow the night 后，从 Istanbul 切换到 Sydney，标题、场景和选中状态更新；关闭后能返回 Istanbul。', value: '持续提供场景变化，适合长时间背景使用与被动探索。', limit: '没有等待 5/10/15/30 分钟定时轮播。跟随夜晚是一种选城策略，不是当前城市的昼夜模拟。' },
  { id: '08', category: 'output', layer: '输出层', title: '场景输出与外部使用', status: 'documented', badge: '入口 / 说明', file: '08-scene-export.png', summary: '1080p PNG 保存、全屏、悬浮播放器，以及 OBS 使用说明。', observation: '保存面板标注 PNG 1920×1080，触发快捷键后出现下载链接。界面还有 Mini player 和 Fullscreen；FAQ 说明城市地址追加 ?obs 可作为 OBS 浏览器源。', value: '把体验延伸到桌面背景、直播和其他展示场景。', limit: '未验证导出文件完整性、悬浮窗兼容性或 OBS 音频路由。离线和安装能力为站方说明，尚未断网实测。' },
];

export const directions = [
  { id: 'workspace', label: '优先验证', title: '个人专注空间', short: '把环境与用户的任务关联。', who: '写作者、阅读者、开发者', effort: '低 → 中', foundation: '已有的场景、音乐、混音、计时', description: '把“进入页面后逐项调节”，变为“选择任务后恢复熟悉的环境”。先围绕个人重复使用的习惯构建。', items: ['整套环境的保存与恢复', '写作、阅读、编程等任务预设', '轻量会话记录，承接下一次使用'], validation: '用户是否重复启动同一个预设，并在后续工作中主动回来使用？', risk: '先证明预设比独立控件更有用，再考虑更复杂的任务管理。', next: '本页的环境组合演示，就是这一方向的最小可交互示例。' },
  { id: 'components', label: '适合库化', title: '可嵌入的场景组件', short: '让其他网页拥有环境能力。', who: '网页工具与产品开发者', effort: '中 → 高', foundation: '场景呈现、音频控制、状态管理', description: '提供可组合的场景与音频模块，使写作工具、学习页面等能按自己的流程调用环境。接口仍是建议，未确认原站已经提供 SDK。', items: ['场景加载、切换和动效控制接口', '音乐与环境声的独立生命周期', '序列化配置、事件通知和宿主联动'], validation: '两个不同宿主产品能否用同一套接口完成接入，而无需复制大量应用代码？', risk: '浏览器音频限制、资源占用、宿主兼容性与明确的源码/内容授权，需要先解决。', next: '先定义最小配置协议，再用一个写作页验证接入。' },
  { id: 'creator', label: '场景明确', title: '创作者背景工具', short: '为直播和录制准备稳定的背景。', who: '直播、录屏和视频创作者', effort: '中', foundation: '全屏画面、OBS 说明、声音控制', description: '围绕准备直播、正式开始、休息和结束这些状态，组织可恢复的背景和声音方案。', items: ['直播状态对应的场景预设', '干净的展示链接与输出尺寸', '快速静音、切换和恢复'], validation: '创作者是否愿意在下一次直播中继续使用，而不是只尝鲜一次？', risk: '必须验证 OBS 启动、音频路由、长期稳定性及内容使用授权。', next: '做一次真实直播工作流验证，优先解决开播和切换的确定性。' },
  { id: 'rooms', label: '后续探索', title: '共同专注房间', short: '共享节奏，保留安静的陪伴。', who: '学习搭档、小型远程团队', effort: '高', foundation: '在线人数与专注计时的体验基础', description: '让几个人共享一个场景和计时状态，围绕在场感与共同作息建立回访，而非先加入复杂聊天。', items: ['房间链接与加入/退出', '共享专注阶段和倒计时', '个人音量偏好与轻量在场状态'], validation: '固定搭档是否持续共同启动专注，并愿意约定下一次？', risk: '需要新增实时服务、状态同步和权限边界；原站人数显示不代表已有房间基础设施。', next: '先限定小房间和共享计时，避免同时构建完整社交产品。' },
  { id: 'editor', label: '长期方向', title: '场景编辑器与内容生态', short: '让内容逐步从作者扩展到社区。', who: '像素创作者、场景爱好者', effort: '高', foundation: '地域场景内容和声音组合', description: '允许创作者按照统一规范组合、发布和分享场景。先让场景格式稳定，再考虑市场或内容平台。', items: ['场景与声源的内容规范', '受控的编辑和预览流程', '来源、版本和授权信息'], validation: '外部创作者能否做出质量稳定的场景，并被其他人持续使用？', risk: '编辑器、资源约束、审核与授权的成本都高，不宜作为首个版本。', next: '先制作一个不依赖作者手工改应用代码的场景包样例。' },
];
