import {VIEWS} from './views.js?v=1.5.1';
export function registerAgentTools(api){
 const context=document.modelContext;if(!context?.registerTool)return;
 const abort=new AbortController();window.addEventListener('pagehide',()=>abort.abort(),{once:true});
 const tools=[
  {name:'read_shoreline_state',description:'Read the current coastal simulation conditions, camera, pause state and measured rendering statistics.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>api.read()},
  {name:'set_shoreline_view',description:'Choose one of four ocean compositions or the secondary shoreline inspections.',inputSchema:{type:'object',properties:{view:{type:'string',enum:Object.keys(VIEWS)}},required:['view'],additionalProperties:false},execute:async({view})=>{if(!VIEWS[view])throw new Error('Unknown viewpoint');const duration=api.view(view);await new Promise(r=>setTimeout(r,duration+80));return api.read();}},
  {name:'pause_shoreline',description:'Freeze or resume waves, foam, spray and wetness while keeping the camera usable.',inputSchema:{type:'object',properties:{paused:{type:'boolean'}},required:['paused'],additionalProperties:false},execute:({paused})=>{if(typeof paused!=='boolean')throw new Error('paused must be boolean');api.pause(paused);return api.read();}},
  {name:'configure_shoreline',description:'Adjust sea state, wind direction, tide, independent cloud coverage, lighting and rendering quality using the same controls as the interface. Fluid conditions blend gradually.',inputSchema:{type:'object',properties:{clouds:{type:'number',minimum:0,maximum:1},strength:{type:'number',minimum:.5,maximum:1.65},wind:{type:'number',minimum:-35,maximum:35},tide:{type:'number',minimum:-.25,maximum:.3},lighting:{type:'string',enum:['afternoon','daylight','overcast']},quality:{type:'string',enum:['low','balanced','high']}},additionalProperties:false},execute:input=>{for(const key of Object.keys(input)){if(!['strength','wind','tide','clouds','lighting','quality'].includes(key))throw new Error('Unknown setting');}for(const [k,a,b] of [['clouds',0,1],['strength',.5,1.65],['wind',-35,35],['tide',-.25,.3]])if(input[k]!==undefined&&(!Number.isFinite(input[k])||input[k]<a||input[k]>b))throw new Error(k+' is outside its range');if(input.lighting&&!['afternoon','daylight','overcast'].includes(input.lighting))throw new Error('Unknown lighting');if(input.quality&&!['low','balanced','high'].includes(input.quality))throw new Error('Unknown quality');api.configure(input);return api.read();}}
 ];
 if(api.measure)tools.push({name:'measure_shoreline_performance',description:'Measure frame pacing, CPU submission, GPU rendering, memory and simulation progress over a stationary interval.',inputSchema:{type:'object',properties:{seconds:{type:'number',minimum:5,maximum:30}},additionalProperties:false},annotations:{readOnlyHint:true},execute:({seconds=20})=>{api.measure(seconds).catch(console.error);return {measuring:true,seconds};}});
 for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:abort.signal})).catch(()=>{});}catch{}}
}
