export const modules = [
  { id: 'architecture', index: 0, number: '01', title: '大模型原理与架构', english: 'LLM Architecture', icon: 'layers', group: 'model', summary: '理解模型如何表示信息、分配注意力并生成下一个词。', tags: ['Attention', 'KV Cache', 'MoE'], why: '模型原理决定了上下文、显存和推理行为。理解内部机制，才能解释工程现象，而不只是调用接口。', concepts: [['注意力机制', '理解 Q、K、V 如何交互，为什么要做缩放，以及多头注意力的作用。'], ['缓存与架构', '认识 KV Cache、GQA、MLA 与 MoE，比较它们的资源开销和取舍。'], ['输入与生成', '串起分词、位置编码、归一化和采样，理解一次生成的完整过程。']], question: 'KV Cache 保存了什么？输入变长、并发增加时，显存为什么会增长？', steps: ['先画出一个 Transformer 模块与张量流向。', '再选注意力或 KV Cache 做一次小规模计算。', '最后联系上下文长度、速度和显存，解释取舍。'], outcome: '能从输入 token 到输出概率解释模型计算，并估算主要资源开销。', prerequisite: 'Python、线性代数基础；建议了解神经网络。' },
  { id: 'inference', index: 1, number: '02', title: '推理服务与性能', english: 'Inference & Serving', icon: 'cpu', group: 'production', summary: '围绕显存、吞吐、延迟与成本，让模型稳定地服务用户。', tags: ['量化', '批处理', 'GPU'], why: '模型能生成答案只是起点。面对真实流量，还需要判断瓶颈在哪、优化是否有效、质量是否受影响。', concepts: [['推理阶段', '区分处理输入的 Prefill 与逐步生成的 Decode，理解二者不同的资源需求。'], ['服务策略', '认识连续批处理、分页缓存、前缀缓存和推测解码。'], ['性能权衡', '结合量化、并行和显存预算，比较首 token 延迟、吞吐与成本。']], question: '模型没变，发布后尾延迟却翻倍了。你会先看哪些指标，如何定位原因？', steps: ['先读懂一次请求的延迟与显存构成。', '固定模型与请求集，每次只改变一项配置。', '同时记录质量、延迟、吞吐和资源占用。'], outcome: '能提出有测量依据的优化方案，解释收益和代价。', prerequisite: '模型基本结构；了解服务请求和性能指标。' },
  { id: 'rag', index: 2, number: '03', title: 'RAG 与知识检索', english: 'Retrieval-Augmented Generation', icon: 'search', group: 'application', summary: '把外部知识接入模型，让回答找到依据、跟上信息变化。', tags: ['文档切分', '混合检索', '重排序'], why: '企业知识往往不在模型里。检索增强生成（RAG）先找资料，再据此回答，效果依赖整条检索链路。', concepts: [['准备知识', '选择切分策略，处理表格与文档结构，维护更新中的索引。'], ['找到资料', '比较关键词检索与语义检索，用重排序挑选更相关的片段。'], ['可信回答', '区分检索与生成的评估，考虑用户权限、引用和依据。']], question: '检索出了很多相关片段，回答还是不准确。怎样区分检索问题与生成问题？', steps: ['从少量文档和已知答案的问题开始。', '分别检查是否检索到证据、是否正确使用证据。', '补上引用、权限与知识更新场景。'], outcome: '能解释一条 RAG 链路，并定位回答错误来自哪个环节。', prerequisite: '了解模型调用与向量表示；可从应用视角开始。' },
  { id: 'agents', index: 3, number: '04', title: 'Agent 与工具调用', english: 'Agents & Tool Use', icon: 'nodes', group: 'application', summary: '让模型通过工具完成任务，同时管理状态、失败和结束条件。', tags: ['工具调用', 'MCP', '记忆'], why: '当模型需要查询资料、调用系统或执行多步任务时，重点会从单次回答转向整个执行流程的可靠性。', concepts: [['工具与协议', '理解工具调用、结构化输出和 MCP，以及工具描述如何影响使用。'], ['状态与记忆', '考虑长期任务保存什么、如何检索，以及多 Agent 协作的代价。'], ['可靠执行', '处理超时、重试、成本预算、终止、审计和人工介入。']], question: '工具调用超时后，Agent 应该重试、换工具，还是结束任务？如何避免重复操作？', steps: ['先设计只有少量工具的明确任务。', '画出执行状态、错误处理与停止条件。', '加入失败案例，检查重试、成本和结果。'], outcome: '能设计一个边界清楚、失败可解释的工具执行流程。', prerequisite: '了解 API、结构化数据与基本错误处理。' },
  { id: 'training', index: 4, number: '05', title: '微调、后训练与对齐', english: 'Fine-tuning & Alignment', icon: 'tune', group: 'model', summary: '根据任务、数据和预算，判断如何改变模型的能力与行为。', tags: ['LoRA', 'RLHF', 'DPO'], why: '并非所有问题都需要训练。这个模块帮助比较提示、检索与训练方案，并理解数据和优化目标的作用。', concepts: [['参数高效微调', '理解 LoRA、QLoRA 等方法如何减少训练资源需求。'], ['偏好与奖励', '认识 RLHF、DPO、GRPO 与可验证奖励，比较所需数据与目标。'], ['选择与验证', '考虑遗忘、奖励投机、蒸馏，以及效果和资源评估。']], question: '面对一个领域任务，你会选择提示优化、RAG 还是微调？判断依据是什么？', steps: ['先写清任务、基线和可用数据。', '比较候选方案的质量、成本与维护要求。', '用固定评测集验证收益与能力退化。'], outcome: '能解释训练方案、数据要求和验证方法，而非只列出算法名字。', prerequisite: '模型原理、损失函数和基本训练流程。' },
  { id: 'evaluation', index: 5, number: '06', title: '评估与可观测性', english: 'Evaluation & Observability', icon: 'chart', group: 'production', summary: '把“好像更好”变成可复核的评估，持续看清系统表现。', tags: ['评测集', '模型裁判', '回归'], why: '缺少稳定评估，就很难判断模型或提示更新是否真的改善了产品，也难以定位用户反馈的问题。', concepts: [['评估设计', '构建评测集，理解模型裁判的偏差与缺少标准答案时的处理。'], ['回归与上线', '观察平均结果之外的失败案例，设计版本变化的检查标准。'], ['线上观察', '结合追踪、成本、反馈和线上实验分析系统行为。']], question: '基准分数提高，用户却觉得效果下降。你如何验证这两个信号？', steps: ['列出实际任务与关键失败类型。', '固定评测集，对比两个版本。', '结合线上反馈解释差异，形成上线判断。'], outcome: '能提出可重复的评估方案，并追踪质量变化的原因。', prerequisite: '了解目标应用；基本统计和实验意识。' },
  { id: 'safety', index: 6, number: '07', title: '安全与责任', english: 'Safety & Security', icon: 'shield', group: 'production', summary: '识别输入、数据与工具的信任边界，设计合适的防护措施。', tags: ['提示注入', '权限边界', '隐私'], why: '应用连接外部内容和真实工具后，需要明确谁有权限、哪些信息可信，以及失败会影响什么。', concepts: [['攻击入口', '理解提示注入、越狱与恶意外部内容的差别。'], ['防护与权限', '考虑输入输出检查、工具权限和敏感数据处理。'], ['评审与测试', '认识红队、可解释性与群体表现差异。']], question: 'Agent 能读网页和内部文档，怎样避免恶意网页诱导它泄露资料？', steps: ['列出数据、用户、外部内容与工具的边界。', '逐条思考失效路径及可用防护。', '用具体案例验证措施是否有效。'], outcome: '能根据具体应用解释风险、权限和验证措施。', prerequisite: '了解应用数据流；涉及 Agent 时先读工具调用模块。' },
  { id: 'multimodal', index: 7, number: '08', title: '多模态与语音', english: 'Multimodal & Voice', icon: 'wave', group: 'model', summary: '从文本走向图像、视频与语音，理解实时交互的额外约束。', tags: ['视觉语言', '语音链路', '实时交互'], why: '不同模态有不同的信息表示、质量指标和时序要求，语音应用尤其需要处理延迟与用户打断。', concepts: [['视觉输入', '理解图像如何进入语言模型，以及从图像到视频的变化。'], ['语音链路', '串起语音活动检测、识别、模型与语音合成。'], ['实时体验', '考虑流式输出、说话人区分、口音与打断处理。']], question: '实时语音助手的一次响应，时间花在了哪些环节？用户打断时怎么办？', steps: ['先画出多模态或语音的输入输出链路。', '拆分每个环节的质量指标和延迟预算。', '补充噪声、打断和流式输出场景。'], outcome: '能解释实时交互链路，并提出分阶段的评估方法。', prerequisite: '模型与 API 基础；信号处理知识有帮助。' },
  { id: 'systems', index: 8, number: '09', title: 'AI 系统设计', english: 'AI System Design', icon: 'layout', group: 'production', summary: '把模型、数据与工程约束组合成可交付的完整方案。', tags: ['企业问答', '代码助手', 'LLM 网关'], why: '系统设计把各个知识点放在一起：先理解需求，再决定架构，并说明质量、成本、规模和维护。', concepts: [['业务与约束', '澄清用户、数据规模、权限、延迟和成功标准。'], ['组合能力', '比较企业问答、代码助手、文档处理与 Text-to-SQL 等方案。'], ['长期运行', '考虑路由、缓存、限流、故障、评估和持续更新。']], question: '设计一个有用户权限的企业问答系统，你会如何组织数据、检索、回答与评估？', steps: ['先明确用户目标和验收标准。', '画出数据流与关键组件，解释替代方案。', '补齐失败处理、扩展方式和上线验证。'], outcome: '能从业务约束推导架构，清楚说明决策与验证依据。', prerequisite: '了解 RAG、Agent、评估等与目标场景相关的模块。' },
  { id: 'coding', index: 9, number: '10', title: '编程与数据结构', english: 'Coding & Data Structures', icon: 'code', group: 'application', summary: '用小规模实现检验理解，训练从原理到代码的转换。', tags: ['Attention 实现', 'BPE', '缓存'], why: '动手实现会暴露抽象解释中遗漏的状态、维度、边界和复杂度问题，是验证理解的重要一步。', concepts: [['模型组件', '实现注意力、缓存、分词与采样等小组件。'], ['数据与状态', '考虑数据结构选择、内存、并发和状态更新。'], ['验证行为', '通过小样本、异常输入与对照结果检查正确性。']], question: '从零实现一个带因果掩码的注意力计算，你会怎样检查形状与结果？', steps: ['把题意写成输入、输出和约束。', '先完成能解释的小实现。', '用边界案例和复杂度分析验证。'], outcome: '能把概念变成可验证代码，并解释边界和复杂度。', prerequisite: '熟悉一种编程语言；模型相关题需要对应原理。' }
];

export const groups = [
  { id: 'model', number: 'A', name: '理解模型', description: '从模型内部，到训练与多模态', modules: ['architecture', 'training', 'multimodal'] },
  { id: 'application', number: 'B', name: '构建应用', description: '连接知识、工具与可运行的实现', modules: ['rag', 'agents', 'coding'] },
  { id: 'production', number: 'C', name: '走向生产', description: '关注性能、质量、安全与完整架构', modules: ['inference', 'evaluation', 'safety', 'systems'] }
];

export const routes = [
  { id: 'application', name: 'AI 应用开发', heading: '先把知识与工具接入应用', description: '适合准备 AI Engineer、LLM 应用开发，或想把现有产品接入大模型的读者。', modules: ['architecture','rag','agents','evaluation','systems'], reasons: ['理解模型的基本限制','让回答有资料依据','让工具可靠执行','验证真实任务表现','把组件组合成方案'], outcome: '用一个文档问答或工具型助手案例，讲清数据流、质量评估和关键取舍。' },
  { id: 'platform', name: '推理与平台', heading: '围绕性能与可靠性深入', description: '适合准备推理优化、AI 平台与基础设施岗位，或需要分析线上模型服务瓶颈的读者。', modules: ['architecture','inference','coding','evaluation','systems'], reasons: ['理解计算与缓存','识别资源和延迟瓶颈','用实现检验理解','让变化可观测','考虑规模与故障'], outcome: '形成一份性能对比记录，同时说明吞吐、延迟、资源占用和质量变化。' },
  { id: 'research', name: '研究与后训练', heading: '从机制、数据到实验验证', description: '适合准备 Research Engineer、模型微调与后训练岗位，已有基本机器学习与编程基础的读者。', modules: ['architecture','coding','training','evaluation'], reasons: ['看懂模型机制','建立可验证的实现','明确数据与优化目标','对比收益与能力退化'], outcome: '设计一个小实验，解释假设、基线、数据、评测结果与局限。' },
  { id: 'delivery', name: '客户交付与方案', heading: '把业务问题变成可验收方案', description: '适合准备解决方案、应用交付与 FDE 岗位，需要连接技术、业务和客户约束的读者。', modules: ['rag','agents','safety','evaluation','systems'], reasons: ['组织业务知识','定义可执行的任务','厘清数据与权限','明确成功标准','形成完整交付方案'], outcome: '写一页试点方案：目标用户、任务范围、权限约束、验收指标与失败处理。' }
];

export const companyGroups = [
  { name: 'Frontier AI Labs', title: '前沿 AI 实验室', description: '模型能力、研究与规模化工程', number: '01' },
  { name: 'Big Tech AI Organizations', title: '大型科技与互联网公司', description: '大规模产品、平台与应用场景', number: '02' },
  { name: 'AI Infrastructure and Platform Companies', title: 'AI 基础设施与平台', description: '推理服务、数据、工具和检索', number: '03' },
  { name: 'AI-Native Product Companies', title: 'AI 原生产品公司', description: '将模型能力落到具体产品体验', number: '04' },
  { name: 'Forward-Deployed and Enterprise AI', title: '企业交付与应用', description: '客户问题、业务流程和解决方案', number: '05' }
];

export const topicLabels = {
  'LLM Internals and Architecture':'模型架构', 'Inference, Serving and GPU Performance':'推理性能', 'RAG and Retrieval':'RAG 与检索', 'Agents and Tool Use':'Agent 与工具', 'Fine-Tuning, Post-Training and Alignment':'微调与对齐', 'Evaluation and Observability':'评估', 'Safety, Security and Responsible AI':'安全', 'Multimodal, Speech and Voice AI':'多模态与语音', 'AI System Design':'系统设计', 'Coding and Data Structures':'编程', 'ML and DL Fundamentals':'机器学习基础', 'Applied and Forward-Deployed Scenarios':'客户交付', 'Behavioral and Culture':'行为与文化'
};
